"""add a passsecure column

Revision ID: 667c4bbf3aee
Revises: bced7559cb9c
Create Date: 2019-09-15 13:18:04.065955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '667c4bbf3aee'
down_revision = 'bced7559cb9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
